sudo: required

language: generic

env:
  global:
    - secure: ZvKeXCx7JSJfHkw7cfHhQUBhJIPC/BoGpAR91yLDZdcS/+rOqz5eDDXA4VQinhot3g67GiLSXkbX4khNAgDJhexbJHDzn11aoYQpRPdSPQutSiDYtOqAeQtIFSsSDOQtPM7PGHGgGZxW3XegtCMr7x4KTqAOCMbN9woqBel69QPhlFy+icEu5j/AeOQQYpYDjG5g2PtKIkd9X11z8dzLLiCboOaw5du6BRHKh27FEXzUSjceOpkaH06ZS5zxHsjfgmv8ch5Uj0flwkjZAcHLQ4jJ9zRr9hXqBlhAtPAgD+UAdTbwA13Gas5YgIVJZZsVg/NINV4MqJbKDdRxR7Lqi2c6VF4Q+sPiz2Gu7pUm9tCkKckB1UcAgSmLwpKwXvfscaP4QygrpztoB7w9Ts35cSBYWwcFfVUo+vJDk7vi9ZqCcPHkqBmZQ+xAAJUzHfVfl5FTPimLt0vZN+q2bCJmPeo7byijDHiQ+IAdC6lzQxdOVIfJ3TDoi8aXvHyXpOOXfgv7fNy7cOmLlbrDbttRFc0qETci8XgqSGGqFRWr2Zs6dbEI82wJo2IH8L9vh+rYzt0CbeFNEx6EQmqrKs47P4UI1RBG8COUbbxirdDC2Lgy1kur0ZiHV2Gs68NeajA+QTjtuETFvEuGipyB7mamYNR/3fQSzixsCY+Gp1vq2H8=

services:
  - docker

script:
  - set -e
  - export REPO=grandlyon/glsdk-webapp
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo $REPO:$TAG:$TRAVIS_BUILD_NUMBER
  - docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:$TAG
  - docker push $REPO
